version: '3.7'

services:
  elasticsearch-integration:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4@sha256:b2cc68c47ab95e8d3f2a60e7bceab1e45f58a22978351f3564431a1fbf6fe6ba
    container_name: elasticsearch.integration
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=topsecret
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  backend:
    image: arcaflow-opensearch-plugin-integration-test
    build: 
      dockerfile: ./Dockerfile
      context: ./
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch.integration:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=topsecret
    command: "-f /configs/opensearch_example.yaml"
    volumes:
      - ./configs:/configs:Z
    depends_on: 
      elasticsearch-integration: 
        condition: service_healthy
        
volumes:
  elasticsearch-data:
    driver: local
