version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2@sha256:81b3bbd42d4d5e238e7ee31b7e99acab0bac1fca4eb2fa88415bad5482e52b88
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - ELASTIC_USERNAME=elastic
      # - ELASTIC_PASSWORD=topsecret
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9200

volumes:
  elasticsearch-data:
    driver: local