version: '3.7'

services:
  elasticsearch-integration:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3@sha256:2892d2363c3c12c5ed54c64faf89e3a19d633d8dd0d190d0bffe03035ff099b3
    container_name: elasticsearch.integration
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=topsecret
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  backend:
    image: arcaflow-opensearch-plugin-integration-test
    build: 
      dockerfile: ./Dockerfile
      context: ./
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch.integration:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=topsecret
    command: "-f /configs/opensearch_example.yaml"
    volumes:
      - ./configs:/configs:Z
    depends_on: 
      elasticsearch-integration: 
        condition: service_healthy
        
volumes:
  elasticsearch-data:
    driver: local
